### ISSUE TITLE
启动jetty时候出错。

### ISSUE THREAD

**Issue by cnbillow** [b3log/symphony#150]
编译成功后，运行服务器时出现下面的错误。但symphony\target目录下class是存在的。请问是什么问题？
`2016-02-21 17:04:31.549:INFO:oejs.Server:main: jetty-9.0.0.M3
2016-02-21 17:04:35.638:WARN:oejw.DiscoveredAnnotation:main: 
java.lang.ClassNotFoundException: org.b3log.symphony.processor.channel.ArticleChannel$ArticleChannelWebSocketServlet
	at runjettyrun.ProjectClassLoader.loadClass(ProjectClassLoader.java:94)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:101)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:80)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.loadClass(DiscoveredAnnotation.java:82)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.getTargetClass(DiscoveredAnnotation.java:67)
	at org.eclipse.jetty.annotations.WebServletAnnotation.apply(WebServletAnnotation.java:64)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:377)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1318)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:485)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.Server.start(Server.java:307)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58)
	at org.eclipse.jetty.server.Server.doStart(Server.java:274)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at runjettyrun.Bootstrap.main(Bootstrap.java:80)
2016-02-21 17:04:35.638:WARN:oeja.WebServletAnnotation:main: org.b3log.symphony.processor.channel.ArticleChannel$ArticleChannelWebSocketServlet cannot be loaded
2016-02-21 17:04:35.639:WARN:oejw.DiscoveredAnnotation:main: 
java.lang.ClassNotFoundException: org.b3log.symphony.processor.channel.ArticleListChannel$ArticleChannelWebSocketServlet
	at runjettyrun.ProjectClassLoader.loadClass(ProjectClassLoader.java:94)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:101)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:80)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.loadClass(DiscoveredAnnotation.java:82)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.getTargetClass(DiscoveredAnnotation.java:67)
	at org.eclipse.jetty.annotations.WebServletAnnotation.apply(WebServletAnnotation.java:64)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:377)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1318)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:485)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.Server.start(Server.java:307)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58)
	at org.eclipse.jetty.server.Server.doStart(Server.java:274)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at runjettyrun.Bootstrap.main(Bootstrap.java:80)
2016-02-21 17:04:35.639:WARN:oeja.WebServletAnnotation:main: org.b3log.symphony.processor.channel.ArticleListChannel$ArticleChannelWebSocketServlet cannot be loaded
2016-02-21 17:04:35.640:WARN:oejw.DiscoveredAnnotation:main: 
java.lang.ClassNotFoundException: org.b3log.symphony.processor.channel.TimelineChannel$TimelineChannelWebSocketServlet
	at runjettyrun.ProjectClassLoader.loadClass(ProjectClassLoader.java:94)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:101)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:80)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.loadClass(DiscoveredAnnotation.java:82)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.getTargetClass(DiscoveredAnnotation.java:67)
	at org.eclipse.jetty.annotations.WebServletAnnotation.apply(WebServletAnnotation.java:64)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:377)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1318)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:485)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.Server.start(Server.java:307)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58)
	at org.eclipse.jetty.server.Server.doStart(Server.java:274)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
	at runjettyrun.Bootstrap.main(Bootstrap.java:80)
2016-02-21 17:04:35.641:WARN:oeja.WebServletAnnotation:main: org.b3log.symphony.processor.channel.TimelineChannel$TimelineChannelWebSocketServlet cannot be loaded
[INFO ]-[2016-02-21 17:04:36]-[com.alibaba.druid.pool.DruidDataSource:669]: {dataSource-1} inited
[INFO ]-[2016-02-21 17:04:36]-[org.b3log.symphony.SymphonyServletListener:123]: Initialized the context
2016-02-21 17:04:36.882:INFO:oejsh.ContextHandler:main: started o.e.j.w.WebAppContext@1eb049ba{/Symphony,[file:/C:/javasource/symphony/src/main/webapp/],AVAILABLE}
2016-02-21 17:04:36.895:INFO:oejs.ServerConnector:main: Started ServerConnector@5aff0e4c{HTTP/1.1}{0.0.0.0:8080}
`

**Comment by 88250** [comment]
Jetty 版本需要 9+

**Comment by cnbillow** [comment]
Running Jetty 9.0.0.M3 
是在这里添加的http://run-jetty-run.googlecode.com/svn/trunk/updatesite-nightly/ 添加的jetty9支持
![image](https://cloud.githubusercontent.com/assets/5892849/13215789/52a223f4-d99b-11e5-8601-110f924f8bc9.png)

![image](https://cloud.githubusercontent.com/assets/5892849/13215815/7d3660d0-d99b-11e5-8ac7-1476d57b33de.png)

**Comment by cnbillow** [comment]
不会配置Jetty。网上找半天，也没找到方法，如果您知道，请指教一下。谢谢。
![image](https://cloud.githubusercontent.com/assets/5892849/13217618/3020dee0-d9a7-11e5-9100-e096590c4337.png)
![image](https://cloud.githubusercontent.com/assets/5892849/13217625/3bf2722e-d9a7-11e5-8d4a-08cbac3e61aa.png)
![image](https://cloud.githubusercontent.com/assets/5892849/13217627/42f55a6e-d9a7-11e5-81ab-31b8219aaaf4.png)
![image](https://cloud.githubusercontent.com/assets/5892849/13217630/4b78633e-d9a7-11e5-957d-7672290c7602.png)

错误信息
   ____    ___                   __    __  __         ___
  / __/___/ (_)__  ___ ___   __ / /__ / /_/ /___ __  / _ \
 / _// __/ / / _ \(_-</ -_) / // / -_) __/ __/ // /  \_, /
/___/\__/_/_/ .__/___/\__/  \___/\__/\__/\__/\_, /  /___/
           /_/                              /___/
2016-02-22 20:39:04.107:INFO::main: Logging initialized @254ms
   Configuration: C:\Users\aaa\AppData\Local\Temp\eclipseJettyPlugin.config.Symphony__1_.xml
         Version: 9.3.7.v20160115
         Context: /
            Port: 8080
       Classpath: C:/Users/aaa/.m2/repository/com/alibaba/druid/1.0.16/druid-1.0.16.jar
                  C:/Users/aaa/.m2/repository/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar
                  C:/Users/aaa/.m2/repository/com/qiniu/qiniu-java-sdk/7.0.4.1/qiniu-java-sdk-7.0.4.1.jar
                  C:/Users/aaa/.m2/repository/com/squareup/okhttp/okhttp/2.3.0/okhttp-2.3.0.jar
                  C:/Users/aaa/.m2/repository/com/squareup/okio/okio/1.3.0/okio-1.3.0.jar
                  C:/Users/aaa/.m2/repository/com/vdurmont/emoji-java/1.1.1/emoji-java-1.1.1.jar
                  C:/Users/aaa/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar
                  C:/Users/aaa/.m2/repository/commons-lang/commons-lang/2.5/commons-lang-2.5.jar
                  C:/Users/aaa/.m2/repository/javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar
                  C:/Users/aaa/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
                  C:/Users/aaa/.m2/repository/javax/el/el-api/1.0/el-api-1.0.jar
                  C:/Users/aaa/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
                  C:/Users/aaa/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
                  C:/Users/aaa/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
                  C:/Users/aaa/.m2/repository/mysql/mysql-connector-java/5.1.36/mysql-connector-java-5.1.36.jar
                  C:/Users/aaa/.m2/repository/org/b3log/latke-repository-mysql/2.0.1/latke-repository-mysql-2.0.1.jar
                  C:/Users/aaa/.m2/repository/org/b3log/latke/2.0.1/latke-2.0.1.jar
                  C:/Users/aaa/.m2/repository/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
                  C:/Users/aaa/.m2/repository/org/jboss/interceptor/jboss-interceptor-api/1.1/jboss-interceptor-api-1.1.jar
                  C:/Users/aaa/.m2/repository/org/jodd/jodd-core/3.6.6/jodd-core-3.6.6.jar
                  C:/Users/aaa/.m2/repository/org/jodd/jodd-http/3.6.6/jodd-http-3.6.6.jar
                  C:/Users/aaa/.m2/repository/org/jodd/jodd-upload/3.6.6/jodd-upload-3.6.6.jar
                  C:/Users/aaa/.m2/repository/org/json/json/20140107/json-20140107.jar
                  C:/Users/aaa/.m2/repository/org/jsoup/jsoup/1.7.1/jsoup-1.7.1.jar
                  C:/Users/aaa/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
                  C:/Users/aaa/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar
                  C:/Users/aaa/.m2/repository/org/tautua/markdownpapers/markdownpapers-core/1.4.2/markdownpapers-core-1.4.2.jar
                  C:/javasource/symphony/target/classes
2016-02-22 20:39:04.447:INFO:oejs.Server:main: jetty-9.3.7.v20160115
2016-02-22 20:39:05.704:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
2016-02-22 20:39:05.795:INFO:oejs.ServerConnector:main: Started ServerConnector@90e32cd{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/servlet/WebSocketServlet
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:549)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:475)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:86)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.loadClass(DiscoveredAnnotation.java:82)
	at org.eclipse.jetty.webapp.DiscoveredAnnotation.getTargetClass(DiscoveredAnnotation.java:67)
	at org.eclipse.jetty.annotations.WebServletAnnotation.apply(WebServletAnnotation.java:69)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:419)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1339)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at net.sourceforge.eclipsejetty.starter.jetty9.Jetty9Adapter.start(Jetty9Adapter.java:68)
	at net.sourceforge.eclipsejetty.starter.common.AbstractJettyLauncherMain.launch(AbstractJettyLauncherMain.java:84)
	at net.sourceforge.eclipsejetty.starter.jetty9.Jetty9LauncherMain.main(Jetty9LauncherMain.java:42)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.servlet.WebSocketServlet
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:549)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:475)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	... 31 more

**Comment by 88250** [comment]
开发环境的话我建议你使用 maven 命令： mvn jetty:run

**Comment by cnbillow** [comment]
可以了，谢谢。
