### ISSUE TITLE
Jetty9第一次初始化报告数据库插入主键冲突

### ISSUE THREAD

**Issue by linkerlin** [b3log/symphony#307]
[INFO ]-[2016-10-17 13:20:39]-[com.alibaba.druid.pool.DruidDataSource:669]: {dataSource-1} inited
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:287]: Initializing Sym....
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:294]: Database [MYSQL], creates all tables
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_tag, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_referral, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_character, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_liveness, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_notification, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_emotion, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_link, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_domain, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_verifycode, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_vote, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_comment, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_invitecode, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_follow, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_option, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_pointtransfer, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_tag_tag, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_reward, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_client, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_domain_tag, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_tag_article, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_user, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_user_tag, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_article, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_revision, isSuccess=true]
[INFO ]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:298]: Creates table result[tableName=symphony_tag_user_link, isSuccess=true]
[ERROR]-[2016-10-17 13:20:39]-[org.b3log.latke.repository.jdbc.JdbcRepository:149]: add:Duplicate entry 'statisticMemberCount' for key 'PRIMARY'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'statisticMemberCount' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
        at org.b3log.latke.repository.jdbc.util.JdbcUtil.executeSql(JdbcUtil.java:89)
        at org.b3log.latke.repository.jdbc.JdbcRepository.add(JdbcRepository.java:147)
        at org.b3log.latke.repository.AbstractRepository.add(AbstractRepository.java:117)
        at org.b3log.symphony.repository.OptionRepository_$$_javassist_35._d0add(OptionRepository_$$_javassist_35.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:101)
        at org.b3log.symphony.repository.OptionRepository_$$_javassist_35.add(OptionRepository_$$_javassist_35.java)
        at org.b3log.symphony.SymphonyServletListener.initDB(SymphonyServletListener.java:309)
        at org.b3log.symphony.SymphonyServletListener.contextInitialized(SymphonyServletListener.java:116)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:452)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:411)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:378)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1516)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1441)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
        at org.eclipse.jetty.start.Main.start(Main.java:457)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
[ERROR]-[2016-10-17 13:20:39]-[org.b3log.symphony.SymphonyServletListener:407]: Creates database tables failed
org.b3log.latke.repository.jdbc.JDBCRepositoryException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'statisticMemberCount' for key 'PRIMARY'
        at org.b3log.latke.repository.jdbc.JdbcRepository.add(JdbcRepository.java:150)
        at org.b3log.latke.repository.AbstractRepository.add(AbstractRepository.java:117)
        at org.b3log.symphony.repository.OptionRepository_$$_javassist_35._d0add(OptionRepository_$$_javassist_35.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:101)
        at org.b3log.symphony.repository.OptionRepository_$$_javassist_35.add(OptionRepository_$$_javassist_35.java)
        at org.b3log.symphony.SymphonyServletListener.initDB(SymphonyServletListener.java:309)
        at org.b3log.symphony.SymphonyServletListener.contextInitialized(SymphonyServletListener.java:116)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:452)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:411)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:378)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1516)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1441)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
        at org.eclipse.jetty.start.Main.start(Main.java:457)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'statisticMemberCount' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
        at org.b3log.latke.repository.jdbc.util.JdbcUtil.executeSql(JdbcUtil.java:89)
        at org.b3log.latke.repository.jdbc.JdbcRepository.add(JdbcRepository.java:147)

**Comment by linkerlin** [comment]
问题找到了，初始化的时候，没有自动删除旧数据导致的。
