### ISSUE TITLE
你好，我部署到TOMCAT时报了一个错误，麻烦指点一下谢谢

### ISSUE THREAD

**Issue by weiwei5910** [b3log/symphony#426]
[ERROR]-[2017-03-24 20:57:23]-[org.b3log.latke.servlet.AbstractServletListener:86]: Initializes request processors failed
java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1090)
	at javassist.bytecode.ConstPool.read(ConstPool.java:1033)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:149)
	at javassist.bytecode.ClassFile.read(ClassFile.java:737)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:108)
	at org.b3log.latke.ioc.config.Discoverer.discover(Discoverer.java:110)
	at org.b3log.latke.servlet.AbstractServletListener.contextInitialized(AbstractServletListener.java:82)
	at org.b3log.symphony.SymphonyServletListener.contextInitialized(SymphonyServletListener.java:92)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4744)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5206)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1439)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1439)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)

**Comment by 88250** [comment]
使用 JDK8

**Comment by weiwei5910** [comment]
不好意思，我的环境是 
jdk1.8
tomcat 9
mac OS 10.x
