### ISSUE TITLE
生成语音摘要导致连接泄露

### ISSUE THREAD

**Issue by eosbp** [b3log/symphony#814]
[2018-11-27 12:23:54]-[com.zaxxer.hikari.pool.ProxyLeakTask:84]: Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@4d1864af on thread pool-1-thread-10, stack trace follows
java.lang.Exception: **Apparent connection leak detected**
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.b3log.latke.repository.jdbc.util.Connections.getConnection(Connections.java:190)
	at org.b3log.latke.repository.jdbc.JdbcTransaction.<init>(JdbcTransaction.java:61)
	at org.b3log.latke.repository.jdbc.JdbcRepository.beginTransaction(JdbcRepository.java:749)
	at org.b3log.latke.repository.AbstractRepository.beginTransaction(AbstractRepository.java:184)
	at org.b3log.symphony.service.ArticleMgmtService.lambda$genArticleAudio$0(ArticleMgmtService.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

<img width="780" alt="image" src="https://user-images.githubusercontent.com/45379823/49059122-4e497380-f242-11e8-9485-3b4bc650a576.png">

**Comment by eosbp** [comment]
最新版的SQL语句分页有问题<img width="1254" alt="image" src="https://user-images.githubusercontent.com/45379823/49065977-9bd1da80-f25a-11e8-9515-8030b7a2b42d.png">

**Comment by eosbp** [comment]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/45379823/49069072-56fe7180-f263-11e8-8af2-b8afaa74e60b.png">

**Comment by 88250** [comment]
收到，稍后会一并修复。
