### ISSUE TITLE
运行一段时间后 偶发性的dao层异常

### ISSUE THREAD

**Issue by cbamls** [b3log/symphony#845]
偶发性dao层异常，然后就死循环 打这个异常日志，导致应用程序空指针异常，是死锁么？3.4.5版本

```
[org.b3log.latke.repository.jdbc.JdbcRepository:801]: Gets a connection failed
java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 2000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.b3log.latke.repository.jdbc.util.Connections.getConnection(Connections.java:190)
```

**Comment by 88250** [comment]
搜索一下日志中有没有出现类似这样的警告：

```
[WARN ]-[2019-01-03 04:45:14]-[com.zaxxer.hikari.pool.ProxyLeakTask:84]: Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@5f9af3c2 on thread pool-2-thread-3, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        at org.b3log.latke.repository.jdbc.util.Connections.getConnection(Connections.java:190)
        at org.b3log.latke.repository.jdbc.JdbcRepository.getConnection(JdbcRepository.java:799)

``` 

如果有，再看一下这句日志后面有没有出现 `on thread pool-2-thread-3 was returned to the pool (unleaked)`（按之前警告中的线程池还有线程 id 搜索），如果有出现说明没有泄露，只是执行太慢导致的。

**Comment by 88250** [comment]
我先关闭了，如果还需要讨论请直接回帖。
